export const mockBoard: KanbanBoardData = {
  _id: "board_1",
  workspaceId: "ws_1",
  name: "Main Kanban Board",
  description: "Product roadmap, sprint tasks, and real-time activity",
  icon: "📋",
  accentColor: "#ff90e8",
  isArchived: false,
  order: 1,
  createdAt: Date.now(),
  columns: [
    {
      _id: "col_backlog",
      boardId: "board_1",
      name: "Backlog",
      color: "#ffc700",
      wipLimit: 10,
      order: 1,
      createdAt: Date.now(),
      tasks: [
        {
          _id: "task_1",
          boardId: "board_1",
          columnId: "col_backlog",
          title: "Setup GSAP Drag & Drop Animations",
          description:
            "Implement physics-inspired card dragging with shadow translation and FLIP layout reordering.",
          priority: "high",
          status: "Backlog",
          assigneeIds: ["user_1"],
          assignees: [
            {
              _id: "user_1",
              name: "Josh Maia",
              email: "josh@kando.app",
              role: "admin",
            },
          ],
          tags: ["UI", "GSAP", "Animation"],
          dueDate: Date.now() + 86400000 * 3,
          order: 1,
          coverColor: "#ff90e8",
          estimatedHours: 8,
          loggedHours: 2,
          subtaskCount: 4,
          completedSubtaskCount: 2,
          commentCount: 5,
          isArchived: false,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
        {
          _id: "task_2",
          boardId: "board_1",
          columnId: "col_backlog",
          title: "Define Convex Real-time Schema",
          description:
            "Database tables for workspaces, boards, columns, tasks, comments, and activity audit logs.",
          priority: "urgent",
          status: "Backlog",
          assigneeIds: ["user_2"],
          assignees: [
            {
              _id: "user_2",
              name: "Daniel",
              email: "daniel@kando.app",
              role: "member",
            },
          ],
          tags: ["Backend", "Convex"],
          dueDate: Date.now() + 86400000 * 5,
          order: 2,
          coverColor: "#7c3aed",
          estimatedHours: 5,
          loggedHours: 5,
          subtaskCount: 2,
          completedSubtaskCount: 2,
          commentCount: 1,
          isArchived: false,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
      ],
    },
    {
      _id: "col_in_progress",
      boardId: "board_1",
      name: "In Progress",
      color: "#ff90e8",
      wipLimit: 5,
      order: 2,
      createdAt: Date.now(),
      tasks: [
        {
          _id: "task_3",
          boardId: "board_1",
          columnId: "col_in_progress",
          title: "Neobrutalist Button & Card Primitives",
          description:
            "Strict 3px black borders, solid drop shadows, and active click translation micro-interactions.",
          priority: "medium",
          status: "In Progress",
          assigneeIds: ["user_1", "user_2"],
          assignees: [
            {
              _id: "user_1",
              name: "Josh Maia",
              email: "josh@kando.app",
              role: "admin",
            },
            {
              _id: "user_2",
              name: "Daniel",
              email: "daniel@kando.app",
              role: "member",
            },
          ],
          tags: ["Design System", "Tailwind"],
          dueDate: Date.now() + 86400000 * 2,
          order: 1,
          coverColor: "#00e599",
          estimatedHours: 12,
          loggedHours: 8,
          subtaskCount: 6,
          completedSubtaskCount: 4,
          commentCount: 3,
          isArchived: false,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
      ],
    },
    {
      _id: "col_review",
      boardId: "board_1",
      name: "Review",
      color: "#7c3aed",
      wipLimit: 3,
      order: 3,
      createdAt: Date.now(),
      tasks: [
        {
          _id: "task_4",
          boardId: "board_1",
          columnId: "col_review",
          title: "Optimistic State Movement Handler",
          description:
            "Instant client query cache updates with elastic shake rollbacks on network mutation error.",
          priority: "high",
          status: "Review",
          assigneeIds: ["user_1"],
          assignees: [
            {
              _id: "user_1",
              name: "Josh Maia",
              email: "josh@kando.app",
              role: "admin",
            },
          ],
          tags: ["Convex", "React State"],
          dueDate: Date.now() + 86400000,
          order: 1,
          coverColor: "#5465ff",
          estimatedHours: 6,
          loggedHours: 6,
          subtaskCount: 3,
          completedSubtaskCount: 3,
          commentCount: 2,
          isArchived: false,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
      ],
    },
    {
      _id: "col_done",
      boardId: "board_1",
      name: "Done",
      color: "#00e599",
      order: 4,
      createdAt: Date.now(),
      tasks: [
        {
          _id: "task_5",
          boardId: "board_1",
          columnId: "col_done",
          title: "Initial Repository Setup & ESLint Rules",
          description:
            "Strict TypeScript compilation, Prettier formatting, and Husky pre-commit hooks.",
          priority: "low",
          status: "Done",
          assigneeIds: ["user_2"],
          assignees: [
            {
              _id: "user_2",
              name: "Daniel",
              email: "daniel@kando.app",
              role: "member",
            },
          ],
          tags: ["DevOps", "Config"],
          order: 1,
          coverColor: "#a5f3fc",
          estimatedHours: 4,
          loggedHours: 4,
          subtaskCount: 2,
          completedSubtaskCount: 2,
          commentCount: 0,
          isArchived: false,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
      ],
    },
  ],
};
